name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t biz-skeleton .
  build-phar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpize
          ini-values: opcache.enable_cli=1
          coverage: none
      - name: Setup Swoole
        run: |
          sudo apt-get install libcurl4-openssl-dev
          wget https://github.com/swoole/swoole-src/archive/v4.6.7.tar.gz -O swoole.tar.gz
          mkdir -p swoole
          tar -xf swoole.tar.gz -C swoole --strip-components=1
          rm swoole.tar.gz
          cd swoole
          phpize
          ./configure --enable-openssl --enable-http2 --enable-swoole-curl --enable-swoole-json
          make -j$(nproc)
          sudo make install
          sudo sh -c "echo extension=swoole > /etc/php/8.0/cli/conf.d/swoole.ini"
          sudo sh -c "echo swoole.use_shortname='Off' >> /etc/php/8.0/cli/conf.d/swoole.ini"
          php --ri swoole
      - name: Build
        run: |
          docker build . -t build:latest
          docker run --name build --entrypoint php build:latest /opt/www/bin/hyperf.php phar:build --name yh.phar -M .env
          docker cp build:/opt/www/yh.phar .
          php yh.phar


